/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sensors */
        get: operations["listSensors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single sensor */
        get: operations["getSensor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensors/{id}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List readings for a sensor */
        get: operations["listReadings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/readings/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest readings in bulk */
        post: operations["ingestReadings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SensorType: "temperature" | "humidity" | "pressure" | "vibration";
        /** @enum {string} */
        SensorStatus: "online" | "offline" | "degraded";
        Sensor: {
            id: string;
            name: string;
            type: components["schemas"]["SensorType"];
            status: components["schemas"]["SensorStatus"];
            location: string;
            unit: string;
            last_reading?: number | null;
            /** Format: date-time */
            updated_at: string;
        };
        Reading: {
            sensor_id: string;
            value: number;
            /** Format: date-time */
            recorded_at: string;
        };
        ReadingInput: {
            sensor_id: string;
            value: number;
            /** Format: date-time */
            recorded_at: string;
        };
        SensorPage: {
            items: components["schemas"]["Sensor"][];
            total: number;
            page: number;
            page_size: number;
        };
        ReadingList: {
            items: components["schemas"]["Reading"][];
            total: number;
        };
        BulkIngestResult: {
            accepted: number;
            rejected: number;
            errors: {
                index: number;
                message: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSensors: {
        parameters: {
            query?: {
                /** @description Free-text search across sensor name and location. */
                q?: string;
                type?: components["schemas"]["SensorType"];
                status?: components["schemas"]["SensorStatus"];
                /** @description Inclusive start of updated_at range (ISO 8601). */
                start?: string;
                /** @description Inclusive end of updated_at range (ISO 8601). */
                end?: string;
                /** @description 1-based page number. */
                page?: number;
                /** @description Number of items per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of sensors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorPage"];
                };
            };
        };
    };
    getSensor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sensor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sensor"];
                };
            };
            /** @description Sensor not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listReadings: {
        parameters: {
            query?: {
                /** @description Inclusive start of range (ISO 8601). */
                start?: string;
                /** @description Inclusive end of range (ISO 8601). */
                end?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Readings for the sensor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingList"];
                };
            };
            /** @description Sensor not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingestReadings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    readings: components["schemas"]["ReadingInput"][];
                };
            };
        };
        responses: {
            /** @description Ingest result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkIngestResult"];
                };
            };
            /** @description Invalid request body. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
}
